# 02 - Data Cleaning

This notebook loads raw qualifying & race results for the 2023 Bahrain GP,  
checks data quality, and outputs **cleaned datasets** into `data/processed/`.

- Standardizes column names
- Converts times to numeric values
- Handles missing values
- Prepares data for exploratory analysis

### 1. Import & Setup

In [1]:
import pandas as pd
import os

# Paths
raw_path = r"C:\UNI\Code\F1_Race_Predictor\data\raw"
processed_path = r"C:\UNI\Code\F1_Race_Predictor\data\processed"

os.makedirs(processed_path, exist_ok=True)

### 2. Load Raw Data

In [2]:
season = 2023
gp = "Bahrain"

q_results = pd.read_csv(fr"{raw_path}\{season}_{gp}_qualifying.csv")
r_results = pd.read_csv(fr"{raw_path}\{season}_{gp}_race.csv")

print("Qualifying Results:")
display(q_results.head())

print("Race Results:")
display(r_results.head())

Qualifying Results:

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
0,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,1.0,NaN,NaN,0 days 00:01:31.295000,0 days 00:01:30.503000,0 days 00:01:29.708000,NaN,NaN,NaN,NaN
1,11,S PEREZ,PER,perez,Red Bull Racing,3671C6,red_bull,Sergio,Perez,Sergio Perez,...,2.0,NaN,NaN,0 days 00:01:31.479000,0 days 00:01:30.746000,0 days 00:01:29.846000,NaN,NaN,NaN,NaN
2,16,C LECLERC,LEC,leclerc,Ferrari,F91536,ferrari,Charles,Leclerc,Charles Leclerc,...,3.0,NaN,NaN,0 days 00:01:31.094000,0 days 00:01:30.282000,0 days 00:01:30,NaN,NaN,NaN,NaN
3,55,C SAINZ,SAI,sainz,Ferrari,F91536,ferrari,Carlos,Sainz,Carlos Sainz,...,4.0,NaN,NaN,0 days 00:01:30.993000,0 days 00:01:30.515000,0 days 00:01:30.154000,NaN,NaN,NaN,NaN
4,14,F ALONSO,ALO,alonso,Aston Martin,358C75,aston_martin,Fernando,Alonso,Fernando Alonso,...,5.0,NaN,NaN,0 days 00:01:31.158000,0 days 00:01:30.645000,0 days 00:01:30.336000,NaN,NaN,NaN,NaN

Race Results:

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
0,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,1.0,1,1.0,NaN,NaN,NaN,0 days 01:33:56.736000,Finished,25.0,57.0
1,11,S PEREZ,PER,perez,Red Bull Racing,3671C6,red_bull,Sergio,Perez,Sergio Perez,...,2.0,2,2.0,NaN,NaN,NaN,0 days 00:00:11.987000,Finished,18.0,57.0
2,14,F ALONSO,ALO,alonso,Aston Martin,358C75,aston_martin,Fernando,Alonso,Fernando Alonso,...,3.0,3,5.0,NaN,NaN,NaN,0 days 00:00:38.637000,Finished,15.0,57.0
3,55,C SAINZ,SAI,sainz,Ferrari,F91536,ferrari,Carlos,Sainz,Carlos Sainz,...,4.0,4,4.0,NaN,NaN,NaN,0 days 00:00:48.052000,Finished,12.0,57.0
4,44,L HAMILTON,HAM,hamilton,Mercedes,6CD3BF,mercedes,Lewis,Hamilton,Lewis Hamilton,...,5.0,5,7.0,NaN,NaN,NaN,0 days 00:00:50.977000,Finished,10.0,57.0

### 3. Check Data Quality

In [4]:
print("Qualifying Info:")
q_results.info()
print("\nMissing values in Qualifying:")
print(q_results.isna().sum())

print("\nRace Info:")
r_results.info()
print("\nMissing values in Race:")
print(r_results.isna().sum())

Qualifying Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DriverNumber        20 non-null     int64
 1   BroadcastName       20 non-null     object
 2   Abbreviation        20 non-null     object
 3   DriverId            20 non-null     object
 4   TeamName            20 non-null     object
 5   TeamColor           20 non-null     object
 6   TeamId              20 non-null     object
 7   FirstName           20 non-null     object
 8   LastName            20 non-null     object
 9   FullName            20 non-null     object
 10  HeadshotUrl         20 non-null     object
 11  CountryCode         20 non-null     object
 12  Position            20 non-null     float64
 13  ClassifiedPosition  0 non-null      float64
 14  GridPosition        0 non-null      float64
 15  Q1                  20 non-null     object
 16  Q2                  14 non-null     object
 17  Q3                  9 non-null      object
 18  Time                0 non-null      float64
 19  Status              0 non-null      float64
 20  Points              0 non-null      float64
 21  Laps                0 non-null      float64
dtypes: float64(7), int64(1), object(14)
memory usage: 3.6+ KB

Missing values in Qualifying:
DriverNumber           0
BroadcastName          0
Abbreviation           0
DriverId               0
TeamName               0
TeamColor              0
TeamId                 0
FirstName              0
LastName               0
FullName               0
HeadshotUrl            0
CountryCode            0
Position               0
ClassifiedPosition    20
GridPosition          20
Q1                     0
Q2                     6
Q3                    11
Time                  20
Status                20
Points                20
Laps                  20
dtype: int64

Race Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DriverNumber        20 non-null     int64
 1   BroadcastName       20 non-null     object
 2   Abbreviation        20 non-null     object
 3   DriverId            20 non-null     object
 4   TeamName            20 non-null     object
 5   TeamColor           20 non-null     object
 6   TeamId              20 non-null     object
 7   FirstName           20 non-null     object
 8   LastName            20 non-null     object
 9   FullName            20 non-null     object
 10  HeadshotUrl         20 non-null     object
 11  CountryCode         20 non-null     object
 12  Position            20 non-null     float64
 13  ClassifiedPosition  20 non-null     object
 14  GridPosition        20 non-null     float64
 15  Q1                  0 non-null      float64
 16  Q2                  0 non-null      float64
 17  Q3                  0 non-null      float64
 18  Time                17 non-null     object
 19  Status              20 non-null     object
 20  Points              20 non-null     float64
 21  Laps                20 non-null     float64
dtypes: float64(7), int64(1), object(14)
memory usage: 3.6+ KB

Missing values in Race:
DriverNumber           0
BroadcastName          0
Abbreviation           0
DriverId               0
TeamName               0
TeamColor              0
TeamId                 0
FirstName              0
LastName               0
FullName               0
HeadshotUrl            0
CountryCode            0
Position               0
ClassifiedPosition     0
GridPosition           0
Q1                    20
Q2                    20
Q3                    20
Time                   3
Status                 0
Points                 0
Laps                   0
dtype: int64

### 4. Cleaning - Standardize & Fix

In [5]:
# --- Column Name Fixes ---
q_results.rename(columns=lambda x: x.strip().title(), inplace=True)
r_results.rename(columns=lambda x: x.strip().title(), inplace=True)

# --- Ensure Position is int ---
if 'Position' in q_results.columns:
    q_results['Position'] = pd.to_numeric(q_results['Position'], errors='coerce')
if 'Position' in r_results.columns:
    r_results['Position'] = pd.to_numeric(r_results['Position'], errors='coerce')

# --- Convert Times ---
time_cols = ['Q1', 'Q2', 'Q3']
for col in time_cols:
    if col in q_results.columns:
        q_results[col] = pd.to_timedelta(q_results[col], errors='coerce')

if 'FastestLapTime' in r_results.columns:
    r_results['FastestLapTime'] = pd.to_timedelta(r_results['FastestLapTime'], errors='coerce')

# --- Add Numeric Seconds Columns ---
for col in time_cols:
    if col in q_results.columns:
        q_results[col + "_sec"] = q_results[col].dt.total_seconds()

if 'FastestLapTime' in r_results.columns:
    r_results['FastestLapTime_sec'] = r_results['FastestLapTime'].dt.total_seconds()

### 5. Encode Status (Finished/DNF)

In [6]:
if 'Status' in r_results.columns:
    r_results['Finished'] = r_results['Status'].apply(lambda x: 0 if 'DNF' in str(x) or 'Retired' in str(x) else 1)

### 6. Save Cleaned Data

In [7]:
q_results.to_csv(fr"{processed_path}\{season}_{gp}_qualifying_clean.csv", index=False)
r_results.to_csv(fr"{processed_path}\{season}_{gp}_race_clean.csv", index=False)

print("âœ… Cleaned data saved to:", processed_path)

âœ… Cleaned data saved to: C:\UNI\Code\F1_Race_Predictor\data\processed